app/app/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from ckeditor_uploader.views import upload, browse
from django.views.i18n import JavaScriptCatalog
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/upload/', upload, name="ckeditor_upload"),
    path('ckeditor/browse/', browse, name="ckeditor_browse"),
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]


urlpatterns += i18n_patterns(
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('', include('user.urls')),
    path('project/', include('project.urls')),
    path('accounts/', include('allauth.urls')),
    path('utils/', include('utils.urls')),
    path('task/', include('task.urls')),
    path('history/', include('history.urls')),
    path('notification/', include('notification.urls')),
    prefix_default_language=False,
)

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/user/urls.py
from django.urls import path
from user.login.views import LoginView
from user.register.views import RegisterView
from user.profile.views import UserProfile, UpdateOwnProfile, OwnProfile, UpdatePass
from user.resetpassword.views import forgotPassword, resetpassword_validate, resetPassword # noqa: 501
from .views import CollaboratorViewSetAPI, LogoutView, HomeView, trigger_error


app_name = 'user'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('sentry-debug', trigger_error),
    path('signin/', LoginView.as_view(), name='signin'),
    path('signup/', RegisterView.as_view(), name='signup'),
    path('signout/', LogoutView.as_view(), name='signout'),
    path('profile/', OwnProfile.as_view(), name='profile'),
    path('updatepass/', UpdatePass.as_view(), name='updatepass'),
    path('updateprofile/', UpdateOwnProfile.as_view(), name='updateprofile'),
    path('userprofile/<int:pk>', UserProfile.as_view(), name='userprofile'),
    path('collaborator/', CollaboratorViewSetAPI.as_view(), name='collaborator'), # noqa: 501
    path('forgotPassword/', forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', resetpassword_validate, name='resetpassword_validate'), # noqa: 501
    path('resetPassword/', resetPassword, name='resetPassword'),

]

app/user/resetpassword/views.py
from django.contrib.auth import logout
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect
from django.http import HttpResponse
from user.forms import ForgetForm, ResetPassForm
from ..models import User
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import get_template
from django.core.signing import Signer

signer = Signer(salt='extra')


def forgotPassword(request):
    if request.user.is_authenticated:
        return redirect('/project/')
    if request.method == 'POST':
        email = request.POST['email']
        if User.objects.filter(email=email).exists():
            user = User.objects.get(email__exact=email)

            # Reset password email
            current_site = get_current_site(request)
            mail_subject = 'Reset Your Password'
            context_message = {
                'user': user,
                'domain': current_site,
                # 'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'uid': signer.sign(int(user.pk)),
                'token': default_token_generator.make_token(user),
            }
            messages = get_template('authentication/reset_password/email_reset_password.html').\
                render(context_message)  # noqa: 501
            send_email = EmailMessage(mail_subject, messages, to=[email])
            send_email.content_subtype = 'html'
            send_email.send(fail_silently=False)
            return HttpResponse('Password reset email has been sent to your email address.', status=200)  # noqa: 501
        else:
            return HttpResponse('Account does not exist!', status=400)
    return render(request, 'authentication/reset_password/reset_password.html', {'form': ForgetForm()})  # noqa: 501


def resetpassword_validate(request, uidb64, token):
    try:
        uid = int(signer.unsign(uidb64))
        user = User.objects.get(id=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uidb64'] = signer.sign(uid)
        messages.success(request, 'Please reset your password')
        return redirect('/resetPassword/')
    else:
        messages.error(request, 'This link has been expired!')
        return redirect('/signin/')


def resetPassword(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid = int(signer.unsign(request.session.get('uidb64')))
            user = User.objects.get(id=uid)
            user.set_password(password)
            user.save()
            return HttpResponse('Ok', status=200)
        else:
            return HttpResponse('Bad request', status=400)
    else:
        if request.user.is_authenticated:
            logout(request)
        return render(request, 'authentication/reset_password/new_password.html',
                      {'form': ResetPassForm()})  # noqa: 501

app/templates/authentication/reset_password/email_reset_password.html
{% load static %}
{% autoescape off %}
<style>html,body { padding: 0; margin:0; }</style>
<div style="font-family:Arial,Helvetica,sans-serif; line-height: 1.5; font-weight: normal; font-size: 15px; color: #2F3044; min-height: 100%; margin:0; padding:0; width:100%; background-color:#edf2f7">
	<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;margin:0 auto; padding:0; max-width:600px">
		<tbody>
			<tr>
				<td align="left" valign="center">
					<div style="text-align:left; margin: 0 20px; padding: 40px; background-color:#ffffff; border-radius: 6px">
						<!--begin:Email content-->
						<div style="padding-bottom: 30px; font-size: 17px;">
							<strong>Hello, {{user.first_name}}!</strong>
						</div>
						<div style="padding-bottom: 30px">You are receiving this email because we received a password reset request for your account. To proceed with the password reset please click on the button below:</div>
						<div style="padding-bottom: 40px; text-align:center;">
							<a href="http://{{domain}}{% url 'user:resetpassword_validate' uidb64=uid token=token %}" rel="noopener" style="text-decoration:none;display:inline-block;text-align:center;padding:0.75575rem 1.3rem;font-size:0.925rem;line-height:1.5;border-radius:0.35rem;color:#ffffff;background-color:#009EF7;border:0px;margin-right:0.75rem!important;font-weight:600!important;outline:none!important;vertical-align:middle" target="_blank">Reset Password</a>
						</div>
						<div style="border-bottom: 1px solid #eeeeee; margin: 15px 0"></div>
						<div style="padding-bottom: 50px; word-wrap: break-all;">
							<p style="margin-bottom: 10px;">Button not working? Try pasting this URL into your browser:</p>
							<a href="http://{{domain}}{% url 'user:resetpassword_validate' uidb64=uid token=token %}" rel="noopener" target="_blank" style="text-decoration:none;color: #009EF7">http://{{domain}}{% url 'user:resetpassword_validate' uidb64=uid token=token %}</a>
						</div>
						<!--end:Email content-->
						<div style="padding-bottom: 10px">Kind regards,
							<br>Clark Le
							<tr>
								<td align="center" valign="center" style="font-size: 13px; text-align:center;padding: 20px; color: #6d6e7c;">
									<p>1, Pham Hong Thai Q9, HCM</p>
									<p>Copyright &copy;
									<a href="#" rel="noopener" target="_blank">Clark</a></p>
								</td>
							</tr>
						</div>
					</div>
				</td>
			</tr>
		</tbody>
	</table>
</div>
{% endautoescape %}

app/templates/authentication/reset_password/new_password.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block css %}
    <link rel="canonical" href="https://preview.keenthemes.com/metronic8" />
    <link rel="shortcut icon" href="{% static 'assets/media/logos/favicon.ico' %}" />
    <!--begin::Fonts(mandatory for all pages)-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700" />
    <!--end::Fonts-->
    <!--begin::Global Stylesheets Bundle(mandatory for all pages)-->
    <link href="{% static 'assets/plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
    <!--end::Global Stylesheets Bundle-->
{% endblock %}
{% block body %}
    <!--begin::Body-->
    <div class="d-flex flex-column-fluid flex-lg-row-auto justify-content-center justify-content-lg-end p-12">
        <!--begin::Wrapper-->
        <div class="bg-body d-flex flex-center rounded-4 w-md-600px p-10">
            <!--begin::Content-->
            <div class="w-md-400px">
                <!--begin::Form-->
                <form class="form w-100" novalidate="novalidate" id="kt_new_password_form" data-kt-redirect-url="#" action="#">
                    {% csrf_token %}
                    <!--begin::Heading-->
                    <div class="text-center mb-10">
                        <!--begin::Title-->
                        <h1 class="text-dark fw-bolder mb-3">Setup New Password</h1>
                        <!--end::Title-->
                        <!--begin::Link-->
                        <div class="text-gray-500 fw-semibold fs-6">Have you already reset the password ?
                            <a href="#" class="link-primary fw-bold">Sign in</a></div>
                        <!--end::Link-->
                    </div>
                    <!--begin::Heading-->
                    <!--begin::Input group-->
                    <div class="fv-row mb-8" data-kt-password-meter="true">
                        <!--begin::Wrapper-->
                        <div class="mb-1">
                            <!--begin::Input wrapper-->
                            <div class="position-relative mb-3">
                                {{ form.password }}
                                <span class="btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2" data-kt-password-meter-control="visibility">
                                    <i class="bi bi-eye-slash fs-2"></i>
                                    <i class="bi bi-eye fs-2 d-none"></i>
                                </span>
                            </div>
                            <!--end::Input wrapper-->
                            <!--begin::Meter-->
                            <div class="d-flex align-items-center mb-3" data-kt-password-meter-control="highlight">
                                <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
                                <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
                                <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
                                <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px"></div>
                            </div>
                            <!--end::Meter-->
                        </div>
                        <!--end::Wrapper-->
                        <!--begin::Hint-->
                        <div class="text-muted">Use 8 or more characters with a mix of letters, numbers & symbols.</div>
                        <!--end::Hint-->
                    </div>
                    <!--end::Input group=-->
                    <!--end::Input group=-->
                    <div class="fv-row mb-8">
                        <!--begin::Repeat Password-->
                        {{form.confirm_password}}
                        <!--end::Repeat Password-->
                    </div>
                    <!--end::Input group=-->
                    <!--begin::Input group=-->
                    <div class="fv-row mb-8">
                        <label class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" name="toc" value="1" />
                            <span class="form-check-label fw-semibold text-gray-700 fs-6 ms-1">I Agree &
                                <a href="#" class="ms-1 link-primary">Terms and conditions</a>.
                            </span>
                        </label>
                    </div>
                    <!--end::Input group=-->
                    <!--begin::Action-->
                    <div class="d-grid mb-10">
                        <button type="button" id="kt_new_password_submit" class="btn btn-primary">
                            <!--begin::Indicator label-->
                            <span class="indicator-label">Submit</span>
                            <!--end::Indicator label-->
                            <!--begin::Indicator progress-->
                            <span class="indicator-progress">Please wait...
                                <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                            </span>
                            <!--end::Indicator progress-->
                        </button>
                    </div>
                    <!--end::Action-->
                </form>
                <!--end::Form-->
            </div>
            <!--end::Content-->
        </div>
        <!--end::Wrapper-->
    </div>
    <!--end::Body-->
{% endblock %}
{% block js %}
    <!--begin::Javascript-->
    <script>var hostUrl = "assets/";</script>
    <!--begin::Global Javascript Bundle(mandatory for all pages)-->
    <script src="{% static 'assets/plugins/global/plugins.bundle.js' %}"></script>
    <script src="{% static 'assets/js/scripts.bundle.js' %}"></script>
    <!--end::Global Javascript Bundle-->
    <!--begin::Custom Javascript(used for this page only)-->
    <script src="{% static 'custom_assets/js/authentication/reset_password/new-password.js' %}"></script>
    <!--end::Custom Javascript-->
    <!--end::Javascript-->
{% endblock %}

app/templates/authentication/reset_password/reset_password.html
{% extends 'authentication/base.html' %}
{% load static %}
{% load i18n %}
{% block css %}
    <link rel="canonical" href="https://preview.keenthemes.com/metronic8" />
    <link rel="shortcut icon" href="{% static 'assets/media/logos/favicon.ico' %}" />
    <!--begin::Fonts(mandatory for all pages)-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700" />
    <!--end::Fonts-->
    <!--begin::Global Stylesheets Bundle(mandatory for all pages)-->
    <link href="{% static 'assets/plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
    <!--end::Global Stylesheets Bundle-->
{% endblock %}
{% block body %}
    <!--begin::Body-->
    <div class="d-flex flex-column-fluid flex-lg-row-auto justify-content-center justify-content-lg-end p-12">
        <!--begin::Wrapper-->
        <div class="bg-body d-flex flex-center rounded-4 w-md-600px p-10">
            <!--begin::Content-->
            <div class="w-md-400px">
                <!--begin::Form-->
                <form method="post" class="form w-100" novalidate="novalidate" id="kt_password_reset_form">
                    {% csrf_token %}
                    <!--begin::Heading-->
                    <div class="text-center mb-10">
                        <!--begin::Title-->
                        <h1 class="text-dark fw-bolder mb-3">{% trans 'Forgot Password ?' %}</h1>
                        <!--end::Title-->
                        <!--begin::Link-->
                        <div class="text-gray-500 fw-semibold fs-6">{% trans 'Enter your email to reset your password.' %}</div>
                        <!--end::Link-->
                    </div>
                    <!--begin::Heading-->
                    {% if request.GET.command == 'verification' %}
                        <!--begin::Alert-->
                        <div class="alert alert-dismissible bg-light-success border border-success border-3 d-flex flex-column flex-sm-row w-100 p-5 mb-10">
                            <!--begin::Icon-->
                            <span class="svg-icon svg-icon-2hx svg-icon-success me-4 mb-5 mb-sm-0">
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path opacity="0.3" d="M21.4 8.35303L19.241 10.511L13.485 4.755L15.643 2.59595C16.0248 2.21423 16.5426 1.99988 17.0825 1.99988C17.6224 1.99988 18.1402 2.21423 18.522 2.59595L21.4 5.474C21.7817 5.85581 21.9962 6.37355 21.9962 6.91345C21.9962 7.45335 21.7817 7.97122 21.4 8.35303ZM3.68699 21.932L9.88699 19.865L4.13099 14.109L2.06399 20.309C1.98815 20.5354 1.97703 20.7787 2.03189 21.0111C2.08674 21.2436 2.2054 21.4561 2.37449 21.6248C2.54359 21.7934 2.75641 21.9115 2.989 21.9658C3.22158 22.0201 3.4647 22.0084 3.69099 21.932H3.68699Z" fill="currentColor"></path>
                                <path d="M5.574 21.3L3.692 21.928C3.46591 22.0032 3.22334 22.0141 2.99144 21.9594C2.75954 21.9046 2.54744 21.7864 2.3789 21.6179C2.21036 21.4495 2.09202 21.2375 2.03711 21.0056C1.9822 20.7737 1.99289 20.5312 2.06799 20.3051L2.696 18.422L5.574 21.3ZM4.13499 14.105L9.891 19.861L19.245 10.507L13.489 4.75098L4.13499 14.105Z" fill="currentColor"></path>
                            </svg>
                        </span>
                            <!--end::Icon-->

                            <!--begin::Wrapper-->
                            <div class="d-flex flex-column pe-0 pe-sm-10">
                                <!--begin::Title-->
                                <h5 class="mb-1">Already verified? <a href="{% url 'signin' %}">Login</a></h5>
                                <!--end::Title-->
                                <!--begin::Content-->
                                <span>Password reset email has been sent to your email [{{ request.GET.email }}] address.</span>
                                <!--end::Content-->
                            </div>
                            <!--end::Wrapper-->

                            <!--begin::Close-->
                            <button type="submit" class="position-absolute position-sm-relative m-2 m-sm-0 top-0 end-0 btn btn-icon ms-sm-auto" data-bs-dismiss="alert">
                                <i class="bi bi-x fs-1 text-primary"></i>
                            </button>
                            <!--end::Close-->
                        </div>
                        <!--end::Alert-->
                    {% endif %}
                    <!--begin::Input group=-->
                    <div class="fv-row mb-8">
                        <!--begin::Email-->
                        {{ form.email }}
                        <!--end::Email-->
                    </div>
                    <!--begin::Actions-->
                    <div class="d-flex flex-wrap justify-content-center pb-lg-0">
                        <button type="submit" id="kt_password_reset_submit" class="btn btn-primary me-4">
                            <!--begin::Indicator label-->
                            <span class="indicator-label">{% trans 'Submit' %}</span>
                            <!--end::Indicator label-->
                            <!--begin::Indicator progress-->
                            <span class="indicator-progress">{% trans 'Please wait...' %}
										<span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
                            <!--end::Indicator progress-->
                        </button>
                        <a href="{% url 'user:signin' %}" class="btn btn-light">{% trans 'Cancel' %}</a>
                    </div>
                    <!--end::Actions-->
                </form>
                <!--end::Form-->
            </div>
            <!--end::Content-->
        </div>
        <!--end::Wrapper-->
    </div>
    <!--end::Body-->
{% endblock %}
{% block js %}
    <!--begin::Javascript-->
    <script>let hostUrl = "{% static 'assets/' %}";</script>
    <!--begin::Global Javascript Bundle(mandatory for all pages)-->
    <script src="{% static 'assets/plugins/global/plugins.bundle.js' %}"></script>
    <script src="{% static 'assets/js/scripts.bundle.js' %}"></script>
    <!--end::Global Javascript Bundle-->
    <!--begin::Custom Javascript(used for this page only)-->
{#    <script src="{% static 'assets/js/custom/authentication/reset-password/reset-password.js' %}"></script>#}
    <script src="{% static 'custom_assets/js/authentication/reset_password/my-reset-password.js' %}"></script>
    <!--end::Custom Javascript-->
    <!--end::Javascript-->
{% endblock %}