app/app/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from ckeditor_uploader.views import upload, browse
from django.views.i18n import JavaScriptCatalog
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/upload/', upload, name="ckeditor_upload"),
    path('ckeditor/browse/', browse, name="ckeditor_browse"),
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]


urlpatterns += i18n_patterns(
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('', include('user.urls')),
    path('project/', include('project.urls')),
    path('accounts/', include('allauth.urls')),
    path('utils/', include('utils.urls')),
    path('task/', include('task.urls')),
    path('history/', include('history.urls')),
    path('notification/', include('notification.urls')),
    prefix_default_language=False,
)

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/user/urls.py
from django.urls import path
from user.login.views import LoginView
from user.register.views import RegisterView
from user.profile.views import UserProfile, UpdateOwnProfile, OwnProfile, UpdatePass
from user.resetpassword.views import forgotPassword, resetpassword_validate, resetPassword # noqa: 501
from .views import CollaboratorViewSetAPI, LogoutView, HomeView, trigger_error


app_name = 'user'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('sentry-debug', trigger_error),
    path('signin/', LoginView.as_view(), name='signin'),
    path('signup/', RegisterView.as_view(), name='signup'),
    path('signout/', LogoutView.as_view(), name='signout'),
    path('profile/', OwnProfile.as_view(), name='profile'),
    path('updatepass/', UpdatePass.as_view(), name='updatepass'),
    path('updateprofile/', UpdateOwnProfile.as_view(), name='updateprofile'),
    path('userprofile/<int:pk>', UserProfile.as_view(), name='userprofile'),
    path('collaborator/', CollaboratorViewSetAPI.as_view(), name='collaborator'), # noqa: 501
    path('forgotPassword/', forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', resetpassword_validate, name='resetpassword_validate'), # noqa: 501
    path('resetPassword/', resetPassword, name='resetPassword'),

]

app/templates/authentication/signin/signin.html
{% extends 'authentication/base.html' %}
{% load i18n %}
{% load static  %}
{% load socialaccount %}
{% block css %}
    <link rel="canonical" href="https://preview.keenthemes.com/metronic8" />
    <link rel="shortcut icon" href="{% static 'assets/media/logos/favicon.ico' %}" />
    <!--begin::Fonts(mandatory for all pages)-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700" />
    <!--end::Fonts-->
    <!--begin::Global Stylesheets Bundle(mandatory for all pages)-->
    <link href="{% static 'assets/plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
    <!--end::Global Stylesheets Bundle-->
    <!--begin::Page bg image-->
    <style>
        body {
            background-image: url('{% static 'assets/media/auth/bg10.jpeg'%}');
        }
        [data-theme="dark"] body {
            background-image: url('{%static 'assets/media/auth/bg10-dark.jpeg'%}');
        }
    </style>
    <!--end::Page bg image-->
{% endblock %}

{% block body %}
    <!--begin::Body-->
    <div class="d-flex flex-column-fluid flex-lg-row-auto justify-content-center justify-content-lg-end p-12">
        <!--begin::Wrapper-->
        <div class="bg-body d-flex flex-center rounded-4 w-md-600px p-10">
            <!--begin::Content-->
            <div class="w-md-400px">
                <!--begin::Form-->
                <form class="form w-100" id="kt_sign_in_form">
                    {% csrf_token %}
                    <!--begin::Heading-->
                    <div class="text-center mb-11">
                        <!--begin::Title-->
                        <h1 class="text-dark fw-bolder mb-3">{% trans 'Sign In' %}</h1>
                        <!--end::Title-->
                        <!--begin::Subtitle-->
                        <div class="text-gray-500 fw-semibold fs-6">{% trans 'Your Social Campaigns' %}</div>
                        <!--end::Subtitle=-->
                    </div>
                    <!--begin::Heading-->
                    <!--begin::Login options-->
                    <div class="row g-3 mb-9">
                        <!--begin::Col-->
                        <div class="col-md-6">
                            <!--begin::Google link=-->
                            <a href="{% provider_login_url 'google' method='oauth2' %}" class="btn btn-flex btn-outline btn-text-gray-700 btn-active-color-primary bg-state-light flex-center text-nowrap w-100">
                                <img alt="Logo" src="{% static 'assets/media/svg/brand-logos/google-icon.svg' %}" class="h-15px me-3" />{% trans 'Sign in with Google' %}</a>
                            <!--end::Google link=-->
                        </div>
                        <!--end::Col-->
                        <!--begin::Col-->
                        <div class="col-md-6">
                            <!--begin::Google link=-->
                            <a href="#" class="btn btn-flex btn-outline btn-text-gray-700 btn-active-color-primary bg-state-light flex-center text-nowrap w-100">
                                <img alt="Logo" src="{% static 'assets/media/svg/brand-logos/apple-black.svg' %}" class="theme-light-show h-15px me-3" />
                                <img alt="Logo" src="{% static 'assets/media/svg/brand-logos/apple-black-dark.svg' %}" class="theme-dark-show h-15px me-3" />{% trans 'Sign in with Apple' %}</a>
                            <!--end::Google link=-->
                        </div>
                        <!--end::Col-->
                    </div>
                    <!--end::Login options-->
                    <!--begin::Separator-->
                    <div class="separator separator-content my-14">
                        <span class="w-125px text-gray-500 fw-semibold fs-7">{% trans 'Or with email' %}</span>
                    </div>
                    <!--end::Separator-->
                    <!--begin::Input group=-->
                    <div class="fv-row mb-8">
                        <!--begin::Email-->
                        {{ loginform.email }}
                        <!--end::Email-->
                    </div>
                    <!--end::Input group=-->
                    <div class="fv-row mb-3">
                        <!--begin::Password-->
                        {{ loginform.password }}
                        <!--end::Password-->
                    </div>
                    <!--end::Input group=-->
                    <!--begin::Wrapper-->
                    <div class="d-flex flex-stack flex-wrap gap-3 fs-base fw-semibold mb-8">
                        <div></div>
                        <!--begin::Link-->
                        <a href="{% url 'user:forgotPassword' %}" class="link-primary">{% trans 'Forgot Password ?' %}</a>
                        <!--end::Link-->
                    </div>
                    <!--end::Wrapper-->
                    <!--begin::Submit button-->
                    <div class="d-grid mb-10">
                        <button type="submit" id="kt_sign_in_submit" class="btn btn-primary">
                            <!--begin::Indicator label-->
                            <span class="indicator-label">{% trans 'Sign In' %}</span>
                            <!--end::Indicator label-->
                            <!--begin::Indicator progress-->
                            <span class="indicator-progress">{% trans 'Please wait...' %}
										<span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
                            <!--end::Indicator progress-->
                        </button>
                    </div>
                    <!--end::Submit button-->
                    <!--begin::Sign up-->
                    <div class="text-gray-500 text-center fw-semibold fs-6">{% trans 'Not a Member yet?' %}
                        <a class="link-primary" type="submit" href="{% url 'user:signup' %}">{% trans 'Sign up' %}</a>
                    </div>
                    <!--end::Sign up-->
                </form>
                <!--end::Form-->
            </div>
            <!--end::Content-->
        </div>
        <!--end::Wrapper-->
    </div>
    <!--end::Body-->
{% endblock %}

{% block js %}
    <!--begin::Javascript-->
    <!--begin::Theme mode setup on page load-->
    <script>
        let defaultThemeMode = "light";
        let themeMode;
        if ( document.documentElement )
        {
            if ( document.documentElement.hasAttribute("data-theme-mode"))
            {
                themeMode = document.documentElement.getAttribute("data-theme-mode");
            } else
            {
                if ( localStorage.getItem("data-theme") !== null )
                {
                    themeMode = localStorage.getItem("data-theme");
                } else
                {
                    themeMode = defaultThemeMode;
                }
            }
            if (themeMode === "system")
            {
                themeMode = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
            }
            document.documentElement.setAttribute("data-theme", themeMode); }
    </script>
    <!--end::Theme mode setup on page load-->
    <script>let hostUrl = "{% static 'assets' %}";</script>
    <!--begin::Global Javascript Bundle(mandatory for all pages)-->
    <script src="{% static 'assets/plugins/global/plugins.bundle.js' %}"></script>
    <script src="{% static 'assets/js/scripts.bundle.js' %}"></script>
    <!--end::Global Javascript Bundle-->
    <!--begin::Custom Javascript(used for this page only)-->
    <script src="{% static 'custom_assets/js/authentication/sign-in/myauthen.js' %}"></script>
    <!--end::Custom Javascript-->
    <!--end::Javascript-->
{% endblock %}